<?php

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Luza\FeaturedProduct\ViewModel\FeaturedProductData $viewModel */
$viewModel = $block->getData('view_model');
?>

<div class="luza-featured-product">
    <h2><?= $escaper->escapeHtml($viewModel->getName()) ?></h2>
    <p>
        <?= $escaper->escapeHtml(__('Price')) ?>:
        <?= $escaper->escapeHtml($viewModel->getPrice()) ?>
    </p>
    <p>
        <?= $escaper->escapeHtml(__('Available Stock')) ?>:
        <?= $escaper->escapeHtml($viewModel->getStock()) ?>
    </p>
</div>